import type { Email } from './types';
import { Difficulty, EmailType, PhishingCategory } from './types';

export const MOCK_EMAILS: Email[] = [
  {
    id: '1',
    fromName: 'IT Support',
    fromEmail: 'support@corp-it-security.com',
    subject: 'Urgent: Password Reset Required',
    body: 'Dear Employee, our security systems detected a suspicious login attempt on your account. Please reset your password immediately by clicking the link below to avoid account suspension.',
    date: '10:45 AM',
    type: EmailType.PHISHING,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Sense of extreme urgency',
      'Suspicious sender domain (corp-it-security.com instead of company.com)',
      'Generic greeting "Dear Employee"'
    ],
    displayLink: 'https://company.com/reset-password',
    actualLink: 'https://secure-login-update.net/reset',
    isRead: false,
    isReported: false,
  },
  {
    id: '2',
    fromName: 'Microsoft Outlook',
    fromEmail: 'no-reply@microsoft.com',
    subject: 'New Login Detected',
    body: 'A new login was detected on your account from a device in London, UK. If this was you, you can ignore this email. If not, please review your recent activity.',
    date: '09:15 AM',
    type: EmailType.LEGITIMATE,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.NONE,
    indicators: [],
    isRead: false,
    isReported: false,
  },
  {
    id: '3',
    fromName: 'HR Department',
    fromEmail: 'hr@company-benefits.com',
    subject: 'Updated 2024 Benefits Package',
    body: 'Please find the attached document regarding the updated benefits package for the upcoming year. All employees are required to review and sign the acknowledgment form.',
    date: 'Yesterday',
    type: EmailType.PHISHING,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.SPEAR_PHISHING,
    indicators: [
      'Suspicious attachment name (benefits_update.exe)',
      'Sender domain mismatch',
      'Unexpected request for signature via executable'
    ],
    attachment: {
      name: 'benefits_update.exe',
      type: 'application/x-msdownload'
    },
    isRead: false,
    isReported: false,
  },
  {
    id: '4',
    fromName: 'Robert Chen (CEO)',
    fromEmail: 'ceo.robert@company.com',
    subject: 'Quick Request',
    body: 'Hi, I am in a meeting and need a quick favor. Can you please purchase 5 Apple Gift cards ($100 each) for a client and send me the codes? I will reimburse you by the end of the day. Thanks, Robert.',
    date: '2 days ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.HARD,
    category: PhishingCategory.BEC,
    indicators: [
      'Request for untraceable payment (Gift Cards)',
      'CEO impersonation (Whaling/BEC)',
      'High pressure/Urgency'
    ],
    isRead: false,
    isReported: false,
  },
  {
    id: '5',
    fromName: 'Slack Notifications',
    fromEmail: 'notifications@slack.com',
    subject: 'You have unread messages in #general',
    body: 'You have 3 unread messages in the #general channel. Click below to view them and stay updated with your team.',
    date: '3 days ago',
    type: EmailType.LEGITIMATE,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.NONE,
    indicators: [],
    displayLink: 'https://slack.com/app',
    actualLink: 'https://slack.com/app',
    isRead: false,
    isReported: false,
  },
  {
    id: '6',
    fromName: 'Amazon Web Services',
    fromEmail: 'billing@amozon.com',
    subject: 'Your AWS Invoice is Ready',
    body: 'Your monthly invoice for AWS services is now available. Please log in to the console to view your charges and ensure your payment method is up to date.',
    date: '4 days ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Typo in domain name (amozon instead of amazon)',
      'Generic billing notification'
    ],
    isRead: false,
    isReported: false,
  },
  {
    id: '7',
    fromName: 'Finance Dept',
    fromEmail: 'invoices@company-finance.net',
    subject: 'Overdue Invoice #8821',
    body: 'Your payment for invoice #8821 is 15 days overdue. Please review the attached PDF and settle the balance immediately to avoid late fees.',
    date: '5 days ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Suspicious domain (.net instead of .com)',
      'Urgency regarding "overdue" payment',
      'Attachment used as bait'
    ],
    attachment: {
      name: 'Invoice_8821.pdf.js',
      type: 'text/javascript'
    },
    isRead: false,
    isReported: false,
  },
  {
    id: '8',
    fromName: 'Google Security',
    fromEmail: 'no-reply@accounts.google.com',
    subject: 'Security alert for your linked account',
    body: 'Your Google Account was just signed in to from a new Windows device. If this was you, you don\'t need to do anything. If not, we\'ll help you secure your account.',
    date: '1 week ago',
    type: EmailType.LEGITIMATE,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.NONE,
    indicators: [],
    isRead: false,
    isReported: false,
  },
  {
    id: '9',
    fromName: 'Internal Communications',
    fromEmail: 'announcements@company.com',
    subject: 'Mandatory: New Workplace Policy',
    body: 'Please review the new workplace policy regarding remote work. All employees must acknowledge receipt by Friday.',
    date: '1 week ago',
    type: EmailType.LEGITIMATE,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.NONE,
    indicators: [],
    isRead: false,
    isReported: false,
  },
  {
    id: '10',
    fromName: 'LinkedIn',
    fromEmail: 'messages-noreply@linkedin.com',
    subject: 'You have a new connection request',
    body: 'Sarah Miller wants to connect with you on LinkedIn. View her profile and accept the invitation.',
    date: '2 weeks ago',
    type: EmailType.LEGITIMATE,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.NONE,
    indicators: [],
    isRead: false,
    isReported: false,
  },
  {
    id: '11',
    fromName: 'Dropbox',
    fromEmail: 'no-reply@dropbox-shared.com',
    subject: 'Document shared with you: "Q4_Financial_Report"',
    body: 'A colleague has shared a confidential document with you via Dropbox. Click the button below to sign in and view the file.',
    date: '2 weeks ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Suspicious domain (dropbox-shared.com is not dropbox.com)',
      'Generic "A colleague" instead of a specific name',
      'Baiting with "Confidential" information'
    ],
    displayLink: 'https://dropbox.com/s/q4-report',
    actualLink: 'https://dropbox-verify-user.xyz/login',
    isRead: false,
    isReported: false,
  },
  {
    id: '12',
    fromName: 'Sarah Jenkins (CFO)',
    fromEmail: 'sjenkins@company.com',
    subject: 'Wire Transfer Instructions',
    body: 'I need you to process an urgent wire transfer for a new vendor. The details are attached. This needs to be completed by EOD today. Let me know once done.',
    date: '3 weeks ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.HARD,
    category: PhishingCategory.WHALING,
    indicators: [
      'High-level executive impersonation',
      'Urgent financial request',
      'Unusual process for wire transfers'
    ],
    attachment: {
      name: 'Vendor_Details.zip',
      type: 'application/zip'
    },
    isRead: false,
    isReported: false,
  },
  {
    id: '13',
    fromName: 'Zoom Video Communications',
    fromEmail: 'no-reply@zoom-meeting.us',
    subject: 'Missed Zoom Meeting',
    body: 'You missed a scheduled Zoom meeting. A recording of the meeting and the transcript are available at the link below.',
    date: '1 month ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Suspicious TLD (.us instead of .us or .com)',
      'Baiting with "Missed Meeting" to trigger curiosity/anxiety',
      'Link leads to a credential harvesting site'
    ],
    displayLink: 'https://zoom.us/recording/view',
    actualLink: 'https://zoom-recordings-portal.net/view',
    isRead: false,
    isReported: false,
  },
  {
    id: '14',
    fromName: 'Apple Support',
    fromEmail: 'security@apple-id-support.com',
    subject: 'Your Apple ID has been locked',
    body: 'For your protection, your Apple ID has been locked due to multiple failed login attempts. To unlock your account, please verify your identity.',
    date: '1 month ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.EASY,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Classic "Account Locked" scare tactic',
      'Suspicious domain name',
      'Generic greeting'
    ],
    isRead: false,
    isReported: false,
  },
  {
    id: '15',
    fromName: 'DocuSign',
    fromEmail: 'dse@docusign.net',
    subject: 'Please DocuSign: Employment_Contract_Update.pdf',
    body: 'You have a new document to sign from the HR Department. Please click the link below to review and sign the document electronically.',
    date: '2 months ago',
    type: EmailType.PHISHING,
    difficulty: Difficulty.MEDIUM,
    category: PhishingCategory.GENERAL,
    indicators: [
      'Suspicious sender domain (.net instead of .com)',
      'Unexpected document request',
      'Link leads to a fake login page'
    ],
    displayLink: 'https://docusign.com/sign/contract',
    actualLink: 'https://docusign-secure-viewer.com/auth',
    isRead: false,
    isReported: false,
  }
];
